require "primary._options"
require "primary._keymaps"
require "primary._plugins"
require "primary._colorscheme"
require "primary._cmp"
require "primary._lsp"
require "primary._telescope"
require "primary._treesitter"
